name: lint

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        name: install pnpm
        with:
          version: 10.20.0
          run_install: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: install devDependencies
        run: pnpm install
      - name: type-check
        run: pnpm type-check
      - name: lint
        run: pnpm lint

